# Generated by Django 4.2.4 on 2023-11-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
    ]
